name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Print greetings
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done -bye!"
